### ISSUE TITLE
Can't generate a URL when code includes a percent sign

### ISSUE THREAD

**Issue by achow0** [razetime/APLgolf#5]
If you put a percent sign anywhere in the header, code, or footer section, you can't seem to generate a link. 
Looking into the console, the following error message appears if you click the CMCify button:
```
Uncaught URIError: URI malformed
    at decodeURIComponent (<anonymous>)
    at d (main.js:114:18)
    at e (main.js:383:24)
    at ce (main.js:384:42)
    at HTMLAnchorElement.<anonymous> (main.js:385:126)
```
And a similar error message appears if you click the Postify button:
```
Uncaught URIError: URI malformed
    at decodeURIComponent (<anonymous>)
    at e (main.js:307:24)
    at ce (main.js:308:42)
    at HTMLAnchorElement.<anonymous> (main.js:309:126)
```

**Comment by razetime** [comment]
i've done some changes to prevent this error. do give me links to reproduce the problem if you find the same issue again.

**Comment by achow0** [comment]
Nice, it looks like it is fixed now!
